#' Subset the sample table based on selection criteria
#'
#' This function let you select which samples you want to include in the analysis
#' from those listed in your sample table. Think twice if your analysis requires a selection
#' or not. Use the `selection` argument  carefully, as it can be misleading. Always verify that the correct samples
#' have been selected before proceeding with downstream analysis.
#'
#' @param sample_table A data frame containing sample metadata.
#' @param selection A named list of filtering conditions. Use names "YES" or "NO".
#' "YES" will include samples matching the condition and exlcude all others.
#' "NO" will exclude samples matching the condition. Therefore, "YES" is more restrictive than "NO".
#' @return A filtered data frame with selected samples.
get_sample_subset <- function(sample_table, selection = NULL) {
  if (is.null(selection) || identical(selection, "None")) {
    return(sample_table)
  }

  for (condition in seq_along(selection)) {
    if (names(selection[condition]) == "YES") {
      sample_table <- sample_table %>%
        dplyr::filter(dplyr::if_any(dplyr::everything(), ~ grepl(selection[condition], .)))
    } else {
      sample_table <- sample_table %>%
        dplyr::filter(dplyr::if_all(dplyr::everything(), ~ !grepl(selection[condition], .)))
    }
  }
  return(sample_table_some)
}

#' Load expression data using tximport
#'
#' This function loads transcript quantification data generated by Salmon using `tximport`.
#' It requires a `tx2gene` data frame to map transcripts to genes.
#'
#' @param samplesDir Directory containing quantification files.
#' @param sample_table A data frame with sample metadata.
#' @param tx2gene A data frame with columns TXNAME and GENEID.
#' @return A tximport object with abundance data.
load_tximport_data <- function(samplesDir, sample_table, tx2gene) {
  files <- file.path(samplesDir, sample_table$Folder, "quant.sf")
  names(files) <- sample_table$Folder
  tximport::tximport(files, type = "salmon", tx2gene = tx2gene)
}

#' Filter lowly expressed genes
#'
#' This function removes genes with low expression across samples, which may introduce noise in downstream analyses.
#' A gene is retained if it has at least `min_count` TPMs in at least `min_samples` samples of the analysis.
#'
#' @param dds A DESeqDataSet object.
#' @param min_count Minimum count threshold per sample. Default to 10 TPM.
#' @param min_samples Minimum number of samples that must meet the threshold. Deafult to 3.
#' @return A filtered DESeqDataSet object.
filter_low_counts <- function(dds, min_count = 10, min_samples = 3) {
  keep <- rowSums(counts(dds) >= min_count) >= min_samples
  dds[keep, ]
}
