#' Subset the sample table based on selection criteria
#'
#' This function let you select which samples you want to include in the analysis
#' from those listed in your sample table. Think twice if your analysis requires a selection
#' or not. Use the `selection` argument  carefully, as it can be misleading. Always verify that the correct samples
#' have been selected before proceeding with downstream analysis.
#'
#' @param sample_table A data frame containing sample metadata.
#' @param Include A vector of condition(s) to include samples from `sample_table`.
#' It will include samples matching this/these condition(s) and exclude all others.
#' Default to NULL.
#' @param Exclude A vector of condition(s) to exclude samples from `sample_table`.
#' Default to NULL.
#' @return A filtered data frame with selected samples.
#' @export
get_sample_subset <- function(sample_table, Include = NULL, Exclude = NULL) {
  if (!is.null(Include)) {
    names(Include) <- rep("YES", length(Include))
  }
  if (!is.null(Exclude)){
    names(Exclude) <- rep("NO", length(Exclude))
  }
  selection <- c(Include, Exclude)
  if (is.null(selection)) {
    return(sample_table)
  }

  for (condition in seq_along(selection)) {
    if (names(selection[condition]) == "YES") {
      sample_table <- sample_table %>%
        dplyr::filter(dplyr::if_any(dplyr::everything(), ~ grepl(selection[condition], .)))
    } else {
      sample_table <- sample_table %>%
        dplyr::filter(dplyr::if_all(dplyr::everything(), ~ !grepl(selection[condition], .)))
    }
  }
  return(sample_table)
}


#' Add Salmon output paths to sample table
#'
#' This function adds a `Folder` column to the `sample_table` data frame, indicating the
#' path where Salmon quantification output (e.g. quant.sf) is expected for each sample, based
#' on folder names found in the `sampleDir` path.
#'
#' @param sampleDir Character. Path to the directory containing Salmon output folders, one per sample.
#' @param sample_table Data frame with sample metadata. One of its columns should match the folder names in `sampleDir`.
#' @return A data frame identical to `sample_table`, with an additional `Folder` column containing full paths.
#' Missing folders will result in `NA` entries.
#' @export
add_sample_path <- function(sampleDir, sample_table) {
  folders <- list.dirs(sampleDir, full.names = FALSE, recursive = FALSE)

  # Determine if folders end with "_quant" and normalize names
  if (all(endsWith(folders, "_quant"))) {
    folder_names <- stringr::str_remove(folders, "_quant")
  } else {
    folder_names <- folders
  }

  # Identify which column in sample_table best matches folder names
  match_counts <- sapply(sample_table, function(col) {
    sum(as.character(col) %in% folder_names)
  })

  if (all(match_counts == 0)) {
    stop("No column in 'sample_table' matches folder names in 'sampleDir'.")
  }

  best_match_col <- names(match_counts)[which.max(match_counts)]

  # Create a lookup table with sample names and full folder paths
  folder_table <- data.frame(
    Sample = folder_names,
    Folder = folders,
    stringsAsFactors = FALSE
  )

  # Merge folder paths into sample_table
  sample_table <- merge(
    folder_table,
    sample_table,
    by.x = "Sample",
    by.y = best_match_col,
    all.x = TRUE
  )

  rownames(sample_table) <- sample_table$Folder

  return(sample_table)
}


#' Load expression data using tximport
#'
#' This function loads transcript quantification data generated by Salmon using `tximport`.
#' It requires a `tx2gene` data frame to map transcripts to genes.
#'
#' @param sampleDir Directory containing Salmon quantification files.
#' @param sample_table A data frame with sample metadata.
#' @param tx2gene A data frame with columns TXNAME and GENEID (transcript-to-gene mapping).
#' @return A tximport object with abundance data.
#' @export
load_tximport_data <- function(sampleDir, sample_table, tx2gene) {
  if ("Folder" %in% colnames(sample_table) & all(rownames(sample_table) == sample_table$Folder)) {
    sample_table_dir <- sample_table
  } else {
    sample_table_dir <- add_sample_path(sampleDir = sampleDir, sample_table = sample_table)
  }
  files <- file.path(sampleDir, sample_table_dir$Folder, "quant.sf")
  names(files) <- sample_table$Folder
  tximport::tximport(files, type = "salmon", tx2gene = tx2gene)
}

#' Filter lowly expressed genes
#'
#' This function removes genes with low expression across samples, which may introduce noise in downstream analyses.
#' A gene is retained if it has at least `min_count` TPMs in at least `min_samples` samples of the analysis.
#'
#' @param dds A DESeqDataSet object.
#' @param min_count Minimum count threshold per sample. Default to 10 TPM.
#' @param min_samples Minimum number of samples that must meet the threshold. Deafult to 3.
#' @return A filtered DESeqDataSet object.
#' @export
filter_low_counts <- function(dds, min_count = 10, min_samples = 3) {
  keep <- rowSums(counts(dds) >= min_count) >= min_samples
  dds[keep, ]
}
